pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/LaxmiPrasanna-sudo/Jenkinsbuild.git'
            }
        }

       stage('Build') {
            steps {
                echo 'Building project...'
                // Example build command
                sh 'echo "Build successful!"'
            }
        }
    }
}


